---
framework: jest
preRun:
     command:
        - npm install
        - npm run build
preMerge:
  pattern:
    - "./test/**/*.spec.ts"
postMerge:
  pattern:
    - "./test/**/*.spec.ts"
postRun:
     command:
        - node --version
version: 1.0
