/**
 * Given an object, returns a new object with the same keys
 * and values generated by running each own enumerable property
 * of the object through an `iteratee` function.
 *
 * @param  {Object} obj
 * @param  {Function} fn - invoked to map the new value
 * @return {Object}
 */
export default function mapValues(obj, fn) {
  return Object.keys(obj).reduce((result, key) => {
    result[key] = fn(obj[key], key);
    return result;
  }, {});
}
