exports.CONTINUE_QUIZZ = 'CONTINUE_QUIZZ';
exports.FINISH_QUIZZ = 'FINISH_QUIZZ';
exports.INCREMENT_SCORE = 'INCREMENT_SCORE';
exports.START_QUIZZ = 'START_QUIZZ';
exports.RESTART_QUIZZ = 'RESTART_QUIZZ';
