export const FETCH_TODOS = {
  SUCCESS: 'FETCH_TODOS/SUCCESS',
  FAILURE: 'FETCH_TODOS/FAILURE',
}

export const ADD_TODO = {
  SUCCESS: 'ADD_TODO/SUCCESS',
  FAILURE: 'ADD_TODO/FAILURE',
}

export const DELETE_TODO = {
  SUCCESS: 'DELETE_TODO/SUCCESS',
  FAILURE: 'DELETE_TODO/FAILURE',
}

export const EDIT_TODO = {
  SUCCESS: 'EDIT_TODO/SUCCESS',
  FAILURE: 'EDIT_TODO/FAILURE',
}
