name: Publish Package to npmjs
on:
  # keeping it purely manual for now as to not accidentally trigger a release
  #release:
  #  types: [published]
  workflow_dispatch:

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: npm publish --access public --provenance
